export const resources = [
  {
    id: '1',
    title: 'Learning Singleton Pattern',
    description: "I would like to learn singleton in JS, it's important",
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 3,
    timeToFinish: 120,
    active: true,
  },
  {
    id: '2',
    title: 'Resource 2',
    description: 'Resource 2 Desc',
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 2,
    timeToFinish: 60,
    active: false,
  },
  {
    id: '3',
    title: 'Resource 3',
    description: 'Resource 3 Desc',
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 1,
    timeToFinish: 30,
    active: false,
  },
  {
    id: '4',
    title: 'Resource 4',
    description: 'Resource 4 Desc',
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 1,
    timeToFinish: 30,
    active: false,
  },
  {
    id: '5',
    title: 'Resource 5',
    description: 'Resource 5 Desc',
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 1,
    timeToFinish: 30,
    active: false,
  },
  {
    id: '6',
    title: 'Resource 6',
    description: 'Resource 6 Desc',
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 1,
    timeToFinish: 30,
    active: false,
  },
  {
    id: '7',
    title: 'Resource 7',
    description: 'Resource 7 Desc',
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 1,
    timeToFinish: 30,
    active: false,
  },
  {
    id: '8',
    title: 'Resource 8',
    description: 'Resource 8 Desc',
    link: 'https://link.com',
    image: 'https://image.com',
    priority: 1,
    timeToFinish: 30,
    active: false,
  },
];
